### ISSUE TITLE
View Recycling Question. 

### ISSUE THREAD

**Issue by rev0lgenX** [natario1/Elements#11]
### How do I?
Is there any way to listen to onViewRecycled to unbind the data from viewholder in presenter or anywhere? Am I missing something? 

### Version used
Library version 0.4.0

**Comment by natario1** [comment]
I have added Presenter.onUnbind, Presenter.onAttach and Presenter.onDetach in v0.5.0 (#12). Thanks for the suggestion!

**Comment by rev0lgenX** [comment]
Nice. Thanks a lot. I will check it out.
