### ISSUE TITLE
Loading/Empty presenters not shown?

### ISSUE THREAD

**Issue by mario** [natario1/Elements#5]
First of all, thank you for Elements - while I'm just starting to evaluate it, it looks quite nice and I hope to be able to contribute some features in the future.

As for now:

```
        val adapter = Adapter.builder(this)
                .addSource(Source.fromLiveData(viewModel.conversationsLiveData))
                .addPresenter(ConversationsPresenter(context, ::onElementClick))
                .addPresenter(Presenter.forLoadingIndicator(context, R.layout.loading_state))
                .addPresenter(Presenter.forEmptyIndicator(context, R.layout.message_state))
                .addPresenter(Presenter.forErrorIndicator(context, R.layout.message_state) { view, throwable ->
                    view.messageStateTextView.setText(R.string.nc_oops)
                    view.messageStateImageView.setImageDrawable(context.getDrawable(drawable.ic_announcement_white_24dp))
                })
                .into(view.recyclerView)
```

This is the code I have. Unfortunately neither the loading nor the empty states (when live data is empty) ever appear (even though they should). Any ideas?

**Comment by natario1** [comment]
Hi!

The source returned by `Source.fromLiveData` is a very simple source implementation that does not emit the loading/empty events. To show them, your source must extend `MainSource`, meant to be the main source of your list.

**Comment by mario** [comment]
Thank you for your answer.
