### ISSUE TITLE
Headers are lost when updating values in LiveData

### ISSUE THREAD

**Issue by mario** [natario1/Elements#7]
Hi! So I use MainSource through LiveData 

> class ContactsViewSource<T : Participant>(private val data: LiveData<List<T>>, private val elementType: Int = 0, loadingIndicatorsEnabled: Boolean = true, errorIndicatorEnabled: Boolean = true, emptyIndicatorEnabled: Boolean = true) : MainSource<T>(loadingIndicatorsEnabled, errorIndicatorEnabled, emptyIndicatorEnabled) {

And unfortunately, when the livedata gets updated the headers from another source get lost. Any ideas what is causing this?

**Comment by natario1** [comment]
The issue must be in your header source implementation. How are you adding headers?

**Comment by mario** [comment]
https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/newarch/features/contactsflow/ContactsViewHeaderSource.kt

This is the header source implementation.

**Comment by natario1** [comment]
I think lastHeader can't work like this - it works well when the main source goes from page 0 to 1 to 2 ..., but it won't work if the main source reloads any page.

So you should invalidate it or, better, store one `lastHeader` per page using `source.setKey(Page, Any)`, then build your logic on top of this: when computing headers for page X, take last header from page X-1 with `getKey(page.previous())`

**Comment by mario** [comment]
Thanks for your reply. Let me investigate this a bit more and get back to
you.

**Comment by mario** [comment]
You are right, this indeed seems to be my issue. Fixed now - thanks for the assistance.
